# Generated by Django 2.2.1 on 2019-06-06 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lei', models.CharField(max_length=50, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3)),
                ('maturity', models.DateField()),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bonds.LegalEntity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
