# Generated by Django 2.2.1 on 2019-06-08 10:27

import bonds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='legal_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bond',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.CharField(max_length=12, validators=[bonds.models.IsinValidator.validate]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='lei',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bond',
            name='size',
            field=models.IntegerField(),
        ),
    ]
