# Generated by Django 2.2.1 on 2019-06-09 11:53

import bonds.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('isin', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[bonds.models.IsinValidator.validate])),
                ('size', models.IntegerField()),
                ('currency', models.CharField(max_length=3, validators=[bonds.models.CurrencyValidator.validate])),
                ('maturity', models.DateField()),
                ('lei', models.CharField(max_length=20, validators=[bonds.models.LeiValidator.validate])),
                ('legal_name', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
