# Generated by Django 2.2.1 on 2019-06-09 14:39

import bonds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_bond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='currency',
            field=models.CharField(choices=[('NZD', 'NZD'), ('RSD', 'RSD'), ('RON', 'RON'), ('BOV', 'BOV'), ('MGA', 'MGA'), ('CHW', 'CHW'), ('MWK', 'MWK'), ('XCD', 'XCD'), ('KWD', 'KWD'), ('PLN', 'PLN'), ('TRY', 'TRY'), ('AOA', 'AOA'), ('TJS', 'TJS'), ('BBD', 'BBD'), ('SGD', 'SGD'), ('UAH', 'UAH'), ('ANG', 'ANG'), ('BDT', 'BDT'), ('BAM', 'BAM'), ('PHP', 'PHP'), ('YER', 'YER'), ('UYU', 'UYU'), ('CAD', 'CAD'), ('JOD', 'JOD'), ('GYD', 'GYD'), ('STN', 'STN'), ('PKR', 'PKR'), ('MYR', 'MYR'), ('GEL', 'GEL'), ('LSL', 'LSL'), ('UGX', 'UGX'), ('MOP', 'MOP'), ('IDR', 'IDR'), ('COU', 'COU'), ('SZL', 'SZL'), ('SOS', 'SOS'), ('BSD', 'BSD'), ('AZN', 'AZN'), ('VUV', 'VUV'), ('SAR', 'SAR'), ('CHF', 'CHF'), ('GNF', 'GNF'), ('WST', 'WST'), ('KGS', 'KGS'), ('BHD', 'BHD'), ('OMR', 'OMR'), ('SSP', 'SSP'), ('XPF', 'XPF'), ('NPR', 'NPR'), ('MNT', 'MNT'), ('UYI', 'UYI'), ('LAK', 'LAK'), ('MAD', 'MAD'), ('LRD', 'LRD'), ('EUR', 'EUR'), ('BND', 'BND'), ('SYP', 'SYP'), ('GTQ', 'GTQ'), ('NIO', 'NIO'), ('HRK', 'HRK'), ('KMF', 'KMF'), ('KES', 'KES'), ('LBP', 'LBP'), ('MUR', 'MUR'), ('VND', 'VND'), ('THB', 'THB'), ('BYN', 'BYN'), ('DJF', 'DJF'), ('MXN', 'MXN'), ('MMK', 'MMK'), ('ZWL', 'ZWL'), ('GHS', 'GHS'), ('AUD', 'AUD'), ('MRU', 'MRU'), ('ARS', 'ARS'), ('QAR', 'QAR'), ('SBD', 'SBD'), ('TTD', 'TTD'), ('TZS', 'TZS'), ('PAB', 'PAB'), ('BZD', 'BZD'), ('JPY', 'JPY'), ('LKR', 'LKR'), ('CVE', 'CVE'), ('BWP', 'BWP'), ('ILS', 'ILS'), ('MDL', 'MDL'), ('BTN', 'BTN'), ('USD', 'USD'), ('DKK', 'DKK'), ('TWD', 'TWD'), ('MXV', 'MXV'), ('TMT', 'TMT'), ('PYG', 'PYG'), ('IRR', 'IRR'), ('ZMW', 'ZMW'), ('AMD', 'AMD'), ('VES', 'VES'), ('XOF', 'XOF'), ('RUB', 'RUB'), ('TOP', 'TOP'), ('NGN', 'NGN'), ('ETB', 'ETB'), ('TND', 'TND'), ('GBP', 'GBP'), ('AWG', 'AWG'), ('XAF', 'XAF'), ('BGN', 'BGN'), ('FJD', 'FJD'), ('SHP', 'SHP'), ('DOP', 'DOP'), ('HNL', 'HNL'), ('KHR', 'KHR'), ('FKP', 'FKP'), ('AED', 'AED'), ('NAD', 'NAD'), ('JMD', 'JMD'), ('CRC', 'CRC'), ('SCR', 'SCR'), ('IQD', 'IQD'), ('MKD', 'MKD'), ('CUP', 'CUP'), ('BIF', 'BIF'), ('CUC', 'CUC'), ('MZN', 'MZN'), ('CHE', 'CHE'), ('CLP', 'CLP'), ('CZK', 'CZK'), ('KZT', 'KZT'), ('KPW', 'KPW'), ('BMD', 'BMD'), ('PGK', 'PGK'), ('LYD', 'LYD'), ('MVR', 'MVR'), ('KYD', 'KYD'), ('HTG', 'HTG'), ('PEN', 'PEN'), ('AFN', 'AFN'), ('BRL', 'BRL'), ('UZS', 'UZS'), ('HKD', 'HKD'), ('DZD', 'DZD'), ('EGP', 'EGP'), ('ERN', 'ERN'), ('CDF', 'CDF'), ('ALL', 'ALL'), ('BOB', 'BOB'), ('COP', 'COP'), ('NOK', 'NOK'), ('KRW', 'KRW'), ('UYW', 'UYW'), ('ISK', 'ISK'), ('GMD', 'GMD'), ('SLL', 'SLL'), ('CNY', 'CNY'), ('HUF', 'HUF'), ('ZAR', 'ZAR'), ('SRD', 'SRD'), ('USN', 'USN'), ('INR', 'INR'), ('SEK', 'SEK'), ('SVC', 'SVC'), ('CLF', 'CLF'), ('RWF', 'RWF'), ('SDG', 'SDG'), ('GIP', 'GIP')], max_length=3, validators=[bonds.models.CurrencyValidator.validate]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='size',
            field=models.IntegerField(validators=[bonds.models.SizeValidator.validate]),
        ),
    ]
