# Generated by Django 2.2.1 on 2019-06-08 10:51

import bonds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_auto_20190608_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='id',
        ),
        migrations.AlterField(
            model_name='bond',
            name='currency',
            field=models.CharField(max_length=3, validators=[bonds.models.CurrencyValidator.validate]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[bonds.models.IsinValidator.validate]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='lei',
            field=models.CharField(max_length=20, validators=[bonds.models.LeiValidator.validate]),
        ),
    ]
