# Generated by Django 3.0.1 on 2019-12-24 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=128)),
                ('lei', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('isin', models.CharField(max_length=12)),
                ('size', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('maturity', models.DateField()),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bonds.LegalEntity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='bond',
            constraint=models.UniqueConstraint(fields=('isin', 'user'), name='unique_isin'),
        ),
    ]
